version: 2
jobs:
  build:
   deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "29:97:c7:5d:8b:79:c6:9a:64:4b:db:55:df:84:08:8d"
    - checkout
    - run:
        name: Push Master to Production
        command: |
          git push https://github.com/lucky-hw-kim/scheduler master:production
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
