version: 2
jobs:
  build:
   deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "20:5c:29:d6:81:76:bb:73:13:12:4f:0d:bd:d3:0e:72"
    - checkout
    - run:
        name: Push Master to Production
        command: |
          git push master
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
